export const projects = [
  {
    bg: "/work4/bg.jpg",
    img: "/work4/work.png",
    name: "StartupLanes",
    desc: "This is a company project of StartupLanes where i had worked as a Fullstack web developer. This project is developed on React (frontend), and Laravel and Mysql (backend).",
    technologies: ["React", "Laravel", "MySQL", "AWS"],
    repo: "",
    link: "",
  },
  {
    bg: "/work5/bg.jpg",
    img: "/work5/work.png",
    name: "Food Quest",
    desc: "A web application built with React, Laravel that's provide a platform where user can create an account order fast foods with a number of food category, can track their order.",
    technologies: ["React", "Laravel", "MySQL", "Tailwind CSS"],
    repo: "https://github.com/creativesid/food-quest-react-laravel-app",
    link: "https://food-quest-app.vercel.app/",
  },
  {
    bg: "/work3/bg.jpg",
    img: "/work3/work.png",
    name: "LaraGigs",
    desc: "LaraGigs is a Web Application that offers user to post and get business requirement projects. A user can post their business requirements. This application is built on Laravel and MySQL with Sanctum Authentication.",
    technologies: ["Laravel", "MySQL", "Tailwind CSS"],
    repo: "https://github.com/creativesid/Laravel-Job-Listing-App",
    link: "",
  },
  {
    bg: "/work7/bg.jpg",
    img: "/work7/work.png",
    name: "Furniture Shopy",
    desc: "Furniture Shopy is a ecommerce platform where user can register, find, filter and buy furnitures. This web app is built with using core PHP and mysql and for design part i have used HTML and CSS.",
    technologies: ["Core PHP", "MySQL"],
    repo: "https://github.com/creativesid/furniture-shopy",
    link: "https://furniture-shopy.herokuapp.com/",
  },
  {
    bg: "/work6/bg.jpg",
    img: "/work6/work.png",
    name: "Color Shades Generator",
    desc: "This is fun project where we can find a number of shade of a specific color. Just enter color name or hexacode and copy your shade code.",
    technologies: ["React", "CSS"],
    repo: "https://github.com/creativesid/color-shade-generator",
    link: "https://color-shade-generator.vercel.app/",
  },
];
